tap "caskformula/caskformula"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
# Command-line interface for SQLite
brew "sqlite"
# Interpreted, interactive, object-oriented programming language
brew "python"
# Dependency manager for Cocoa projects
brew "cocoapods"
# Dependency Manager for PHP
brew "composer"
# Lightweight DNS forwarder and DHCP server
brew "dnsmasq", restart_service: true
# Select default apps for documents and URL schemes on macOS
brew "duti"
# Low-level access to audio, keyboard, mouse, joystick, and graphics
brew "sdl2"
# Distributed revision control system
brew "git"
# Open-source build automation tool based on the Groovy and Kotlin DSL
brew "gradle"
# Apache HTTP server
brew "httpd"
# CLI for MySQL with auto-completion and syntax highlighting
brew "mycli"
# Open source relational database management system
brew "mysql@5.7", restart_service: true, link: true
# HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
brew "nginx", restart_service: true
# Platform built on V8 to build network applications
brew "node"
# General-purpose scripting language
brew "php", restart_service: true
# General-purpose scripting language
brew "php@7.2"
# General-purpose scripting language
brew "php@7.3"
# Python dependency management tool
brew "pipenv"
# Persistent key-value database, with built-in net interface
brew "redis"
# User interface to the TELNET protocol
brew "telnet"
# JavaScript package manager
brew "yarn"
cask "gimp"
cask "java8"
cask "xquartz"
